server:
  port: 8086
spring:
  main:
    web-application-type: reactive
  application:
    name: apigatewayEvent
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      routes:
      - id: event-service
        uri: lb://EventService
        predicates:
          - Path=/events/**
      - id: ticket-server
        uri: lb://TicketServer
        predicates:
          - Path=/tickets/**
      - id: venue-server
        uri: lb://VenueServer
        predicates:
          - Path=/venues/**
      - id: attendee-server
        uri: lb://AttendeeServer
        predicates:
          - Path=/attendees/**
      - id: analytics-server
        uri: lb://AnalyticsServer
        predicates:
          - Path=/analytics/**
      discovery:
        locator:
           enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true


